### ISSUE TITLE
Gesture duration control?

### ISSUE THREAD

**Issue by AgileInteractive** [biodiv/contactjs#20]
Can i pass global and/or individual _duration_ properties for the different gestures somewhere?

I.e:
a) I want to set the global timer for a Tap event to register within max 600ms
b) I want to set some specific individual Tap events to 1000ms
(I want neither of the above to mess with timers of other gestures than Tap)

**Comment by biodiv** [comment]
You can set those timers differently for different instances of `Tap`, but I never tried that.
For example, try:

```
let tap = new Tap(domElement);
tap.initialParameters.global["duration"] = [null, 600];
const options = {
  supportedGestures: [tap];
}

const pointerListener = new PointerListener(domElement, options);
```

or if using `contactjs v2.0`:

`tap.initialParameters.global.max["duration"] = 600;`

This should resolve in the tap event being fired **if the finger is removed from the surface** before 600ms.
Be aware that `Press` currently is timed at 600ms, but `Press` fires **if the finger still touches the surface.** So if you want to use them together, maybe you have to adjust `Press`, too.

In your scenario, I _think_ you would have to set up two instances of `PointerListener`, too. One with tap targeting 600ms, one with tap targeting 1000ms. I never tried having two `Tap` instances on one `PointerListener`, but it's worth a shot.

**Comment by AgileInteractive** [comment]
Thanks for the answer!

Just a sidenote: Any chance the 2.0 version could have a more simple and intuive way to set such and similar settings?

**Comment by biodiv** [comment]
> Just a sidenote: Any chance the 2.0 version could have a more simple and intuive way to set such and similar settings?

I have been thinking about this. I see two approaches.

**1. Adhere strictly to the internal parameter structure**
Example:
```
let tap = new Tap(domElement, {
  initialParameters : {
    global : {
      max : {
        duration : 600
      }
    }
  }
});
```
In theory, some gestures can have a minimum duration and a maximum duration, even depending on the evaluated vector (`live`, `global`).

Pro:
- the developer sees that recognition is complex and maybe understands better where to change values to achieve the desired result. This probably applies only to more complex, multi-pointer gestures. 

Con:
- Difficult to use

**2. Ignore the internal parameter structure, and make it as simple as possible**
Example:
```
let tap = new Tap(domElement, {
   maxDuration : 600
});
```

Pro:
- easy to use interface

Con:
- Could sometimes lead to misconceptions on how gestures are recognized, which can result in undesired behaviour


**Currently, I am inclined to implement approach 2 and mention the simplification in the docs.**

**Comment by AgileInteractive** [comment]
If I understand correctly you can then:

```
let tap1 = new Tap(domElement1, {
   maxDuration : 600
});

let tap2 = new Tap(domElement2, {
   maxDuration : 400
});
```

And they would work nice side-by-side.

Certainly, the first option does look cumbersome

**Comment by biodiv** [comment]
https://biodiv.github.io/contactjs/documentation/recognizer-options/#Tap
