### ISSUE TITLE
no documentation for swipeLeft and swipeEvent

### ISSUE THREAD

**Issue by fplord** [biodiv/contactjs#25]
https://biodiv.github.io/contactjs/documentation/contact-js/#Events

the documentation for Events should include `swipeRight` and `swipeLeft` event listeners

**Comment by fplord** [comment]
see https://github.com/biodiv/contactjs/blob/main/src/gestures/Pan.ts#L77 

`this.emit(pointerManager, "swipe");`

**Comment by biodiv** [comment]
thanks for bringing this up, I included `swipe` and its directional events in the list
