### ISSUE TITLE
Issues while migrating to 2.x version

### ISSUE THREAD

**Issue by orangecoloured** [biodiv/contactjs#27]
There's a comment for the 2.x version.

> If you have been using `event.detail.contact` to get information out of the contact instance, this should be replaced with `event.detail.pointerManager`.

But that's how the `event.detail` looks like after I installed `2.0.3`.
<img width="997" alt="Screenshot 2022-09-29 at 12 51 27 AM" src="https://user-images.githubusercontent.com/3314891/192895300-bdf3ac3e-4866-4806-93da-2e583f4f788b.png">

**Comment by biodiv** [comment]
While `event.detail.pointerManager` replaced `event.detail.contact`, the `PointerManager` class differs from the `Contact` class.

Which information did you extract from the contact instance? I can then help with the migration and hopefully update the migration guidelines.

**Comment by orangecoloured** [comment]
I'm using `event.detail.contact.multipointer.globalParameters.center` coordinates before pinch zooming to store the initial coordinates.

**Comment by biodiv** [comment]
I fixed this issues in `v2.1.0`. You can access the center using `event.detail.global.center` or `event.detail.pointerManager.activePointerInput.parameters.global.center`.

Are you using the `npm` package or the js files directly? If the latter, please try the attached version.

[contact-v2.1.0.zip](https://github.com/biodiv/contactjs/files/9681990/contact-v2.1.0.zip)

**Comment by orangecoloured** [comment]
I'm using the npm package, so I'll wait till it's up 👍

**Comment by orangecoloured** [comment]
Perfect! Issue resolved, I'm getting the data.
