### ISSUE TITLE
Issue with `CustomEvent` and SSR

### ISSUE THREAD

**Issue by orangecoloured** [biodiv/contactjs#30]
After installing `2.x` I couldn't build the project. So I started going back in versions.
I'm having this error while building `ReferenceError: CustomEvent is not defined`.
Moving back to `1.4.1` and using `CustomEvent` in my code fixed the issue.
I guess you need to import that type in the contactjs code?

**Comment by SE2Dev** [comment]
`CustomEvent` is a global that is provided by the browser. See [here](https://developer.mozilla.org/en-US/docs/Web/API/CustomEvent/CustomEvent).

A `ReferenceError` would indicate to me that you're seeing this issue at _runtime_, which means it could be the result of a bundler issue.

**Comment by orangecoloured** [comment]
Yeah, this obviously is happening while producing the bundled code.
But the bundler doesn't throw the usage of `CustomEvent` in my project's code.
So only the usage in the 3rd party lib code leads to this error.

While `CustomEvent` is provided by the browser, the lib code should either have checks for the environment type or be environment agnostic. The code is bundled in a non-browser environment, so probably some fallbacks or polyfills should be applied.

**Comment by SE2Dev** [comment]
Ah yeh, it's an SSR issue. `CustomEvent` is not present in the SSR environment. You could try disabling SSR like it mentions in the error. I'm not really sure why it allows you to use `CustomEvent` directly in your code though.

**Comment by orangecoloured** [comment]
The whole point of using frameworks that provide you with SSR output is to have the web pages pre-rendered. So disabling makes no sense in this case. :)
I think preact injects global types on the bundling stage for the project's code. Probably it doesn't do it for all the 3rd party packages.
So maybe these global browser types need to be introduce to the contactjs code? Otherwise it looks like it will fail to bundle in any SSR build.

**Comment by SE2Dev** [comment]
I added a polyfill for `CustomEvent` for non-browser environments in cccbbc60c4e3b787f37df575aed54dd786006622.

**Comment by orangecoloured** [comment]
@biodiv Could you create a new npm release so I can test the SSR?

**Comment by biodiv** [comment]
I just published v2.1.2 which contains https://github.com/biodiv/contactjs/commit/cccbbc60c4e3b787f37df575aed54dd786006622

**Comment by orangecoloured** [comment]
@SE2Dev  Perfect! SSR build completes with no errors.
