### ISSUE TITLE
Pinch in (zoom out) is being registered only after pinch out (zoom in)

### ISSUE THREAD

**Issue by orangecoloured** [biodiv/contactjs#31]
As the title says, pinching out an element does nothing. Only after a pinch in I can then normally pinch out.
You can reproduce this here: https://biodiv.github.io/contactjs/
Try to pinch out the square without pinching in, it won't shrink.
I did a bit of debugging and `pinchstart` doesn't fire in this case.

**Comment by biodiv** [comment]
thanks for reporting. Please try the updated version `v2.1.3`

**Comment by orangecoloured** [comment]
Perfect! Now it works as expected.
Thanks!
