### ISSUE TITLE
recognizer-options default values in Documentation ?

### ISSUE THREAD

**Issue by JonathanOchej** [biodiv/contactjs#36]
Hey, thx again for your amazing work !

I just have a small note about the documentation. What are the default values ​​for the recognizer-options in this page : https://biodiv.github.io/contactjs/documentation/recognizer-options/ ? ( maxDuration, maxDistance, bubbles, etc...) Could be great to add them in the doc.

Thanks

**Comment by biodiv** [comment]
Docs have been updated with default values
