### ISSUE TITLE
Error in TS build

### ISSUE THREAD

**Issue by LEinfeldt** [biodiv/contactjs#37]
Thanks for providing this lib :-). 

When I build my Project (typescript: 4.9.4) with a contactjs dependency, I receive the following error:

```
Error: node_modules/contactjs/dist/index.d.ts:18:1 - error TS1046: Top-level declarations in .d.ts files must start with either a 'declare' or 'export' modifier.

18 enum PointerManagerState {
   ~~~~
```
Could you export or declare these?

**Comment by LEinfeldt** [comment]
Thanks for the quick response :)

**Comment by biodiv** [comment]
Thanks for reporting the issue!
