### ISSUE TITLE
Default delays between Tap and Press are weird

### ISSUE THREAD

**Issue by JonathanOchej** [biodiv/contactjs#39]
I saw in the documentation that nothing seem to happen for tap/press on screen between 200ms and 600ms ?

Is there a specific reason ?

Hammer.js used 250ms max duration for Tap and 251ms min duration for Press.
Maybe it could be good idea to to the same for contact.js ?

**Comment by biodiv** [comment]
Thanks for bringing this up. The main question is if the shorter time of >251ms _feels_  right for the end-user. If I want to trigger a press on the iPhone home screen, I have to wait longer than 251ms. On the other hand, I can trigger a tap after more than 250ms. The same seems to be the case on my Android test devices home screen. I did a quick research and it seems to be that mobile devices use **>=500ms** for `Press`.

I think there should be no gap between tap and press.  Maybe it is good to be consistent with the behavior on mobile devices. That would mean 499 max duration for Tap and 500 min duration for Press.

What are your thoughts on this?

**Comment by JonathanOchej** [comment]
Yeah, it can be a good default values ;) As the author you decide ;)
The point is just to remove the actual default gap between tap and press where nothing happen !
