### ISSUE TITLE
Support for press?

### ISSUE THREAD

**Issue by niklasgrewe** [biodiv/contactjs#4]
Hi thank you for an alternative library for HammerJS. 👍
Could you also support press actions?

**Comment by biodiv** [comment]
I will implement press actions. I would define a press action as follows:

- the user touches the surface with one finger (or pen, or mouse down)
- the user does not move the finger (certain tolerance applied)
- the pointer (finger) stays on the surface for a certain amount of time
- the event fires if the finger/pointer is still on the surface after the defined timespan
- the event does not fire if the finger/pointer is removed before the defined timespan ended, or if the finger/pointer has been moved too much, or if a second finger made contact with the surface

Is this your understanding of a press aswell ?

**Comment by niklasgrewe** [comment]
Yes, absolutely, could you also include `e.preventDefault()`? For example, when I add a press action to a `<a href="/test" />` I get a link preview by default in Safari (iOS). It would be great if we can prevent this as well

**Comment by biodiv** [comment]
I added support for press in the latest build (`/build` folder of this repository ). The required time is currently set to 600ms. For testing, you can adjust this setting in `contact.js` line 1306:
'''
this.initialMinMaxParameters["duration"] = [600, null];
'''
It would be highly appreciated if you tested if 600ms is in your opinion appropriate for a press. I tried it side-by-side to iOS15 and it seemed to be about right to me.

**Comment by biodiv** [comment]
implemented in v1.3.1
