### ISSUE TITLE
Casing for native JS events hook options wrong?

### ISSUE THREAD

**Issue by doompadee** [biodiv/contactjs#40]
The [documentation](https://biodiv.github.io/contactjs/documentation/contact-js/#Options) states that hooks can be added for the native JavaScript events, like `pointerDown` etc. But the actual code uses all lowercase names and the hooks therefore did not work for me at first.

**Comment by TBG-FR** [comment]
You're right ! I also followed [the documentation](https://biodiv.github.io/contactjs/documentation/contact-js/#PointerListener) and used `pointerDown`/`pointerMove`/`pointerUp`/`pointerOut`/`pointerCancel`. Nothing happens, and you do not get any error 😵 

Now with `pointerdown`/`pointermove`/`pointerup`/`pointerout`/`pointercancel` I can catch events ! Thanks 🌞

**Comment by biodiv** [comment]
I will update the docs to represent the correct casing. The code will stay as is regarding this matter.

**Comment by biodiv** [comment]
updated the docs
