### ISSUE TITLE
Built-in event handler management

### ISSUE THREAD

**Issue by igorski** [biodiv/contactjs#7]
Not so much an "issue", but for your consideration.

I noticed that the touch event listeners are attached directly onto the element passed to `PointerListener`. This makes sense as it remains close to the EventTarget interface of the DOM element and gives the programmer the discretion to be responsible for cleaning up the listeners.

However, I can imagine an use case where the DOM element only gets event handlers for the touch events that are managed by PointerListener. It should also be possible to dispose a PointerListener instance throughout an applications lifetime (because the touch enabled elements are added and removed from the DOM depending on application state).

Would it make sense to have an interface added to `PointerListener` that is similar to this:

### PointerListener.on( type, handlerReference )

Where _type_ is the event type and _handlerReference_ is the callback which is invoked whenever the event is dispatched. Since PointerListener has a reference to the element it manages, it can internally invoke `element.addEventListener( type, handler )`.

### PointerListener.off( type, handlerReference )

Which is the inverse of `PointerListener.on` and removes the previously attached listener from the element.

So far, the above doesn't provide any benefit over the current implementation. However:

### PointerListener.destroy()

To be invoked when the PointerListener is no longer needed. This would remove all event listeners attached to the element using `PointerListener.on` allowing for an instant clean up. It also provides a benefit in the case other event handlers were attached to the DOM element (consider drop event handling) that are separate from the responsibilities of contactjs (and that need to be remain while only the touch handling is removed).

**edit** this method could also remove the `touchmove` listeners that are added internally in `addTouchListeners` which don't seem to be removed ?

The above would also greatly help preventing memory leaks (this is of course not a guaranteed problem as this is also up to the implementation, however I feel like offering a self managing event interface would be a welcome addition).

**Comment by biodiv** [comment]
I implemented your suggestion in the latest build for testing.

**Comment by igorski** [comment]
Awesome. Verified in 1.4.0.

Thanks for the quick follow-up!
