### ISSUE TITLE
Wrong event names after minification

### ISSUE THREAD

**Issue by orangecoloured** [biodiv/contactjs#9]
Not sure what's up and how to properly debug this.

I have a preact app and while I dev, the lib is working properly.
But in prod the event handlers bound to the element don't get called.
`touch*` event handlers are working fine.

I set the `DEBUG` to `true`, the `PointerListener` gets initialised and I get the debug info in the prod build.
But it's a lot of data and I'm not sure what to look for to understand the issue.

I tried different options to initialise with, but it makes no difference.

**UPD**

I think it's the minification that is messing up the code.
The event names get optimised, so for example `panup` becomes `qup`.
I'm not an expert in this, but if I'm not mistaken these event names should be assigned as strings and not variables. This way they'll get through the optimisations intact.

**Comment by biodiv** [comment]
Thanks for reporting and debugging! Currently, event names are built using `constructor.name` and `DIRECTION_*` variables, which seems to not work after minification. For minification `gulp-minify` is used. Using its option `mangle:false` should solve the problem. In the next build, I will include this option.

**Comment by orangecoloured** [comment]
Great! Thanks!

Could you also add the debug flag to options? I found the only way to turn it on is to edit the lib code directly in the `node_modules`.

**Comment by biodiv** [comment]
I uploaded a new minified version for testing in the `/build` folder of this repository which should work.

I will add the debug flag to the options.

**Comment by orangecoloured** [comment]
While this can be useful for manual imports, I believe it won't help to solve the issue while using npm/yarn. In this case it depends on the uglifying package that is used in the project. In my case I'm using preact cli which is using TerserPlugin. I'll need to update my webpack config to make TerserPlugin extract the chunk with the contactjs package into a separate one without mangling.

So it looks while the gulp flag can be a solution, it is not universal.

**Comment by biodiv** [comment]
In this case, I think it would be best to implement the event name as a string as you initially suggested. The library should not be rendered unusable by uglifying packages.

**Comment by orangecoloured** [comment]
The latest release fixes the issue. Awesome. Thanks!
